### ISSUE TITLE
🤖 Automation: Dependabot should be able to catch secret variables in created pull requests

### ISSUE THREAD

**Issue by ylazakovich** [ylazakovich/path-of-exile-starter#205]
## Description

https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
Here described solution for workaround action issue

## Details

When dependabot creates pull request he doesn't able to catch secret
As result `IS_REMOTE` variable has empty value = ``

https://github.com/ylazakovich/path-of-exile-starter/actions/runs/10221814387/job/28296036989

```
Caused by:
        java.lang.UnsupportedOperationException: Cannot convert '' to java.lang.Boolean
            at org.aeonbits.owner.util.Util.unsupported(Util.java:139)
            at org.aeonbits.owner.Converters.unsupportedConversion(Converters.java:294)
            at org.aeonbits.owner.Converters.access$400(Converters.java:38)
            at org.aeonbits.owner.Converters$5.tryConvert(Converters.java:161)
            at org.aeonbits.owner.Converters.doConvert(Converters.java:285)
            at org.aeonbits.owner.Converters.convert(Converters.java:280)
            at org.aeonbits.owner.PropertiesInvocationHandler.resolveProperty(PropertiesInvocationHandler.java:89)
            at org.aeonbits.owner.PropertiesInvocationHandler.invoke(PropertiesInvocationHandler.java:67)
            at jdk.proxy3/jdk.proxy3.$Proxy18.isRemote(Unknown Source)
            at io.starter.config.BrowserConfig.<clinit>(BrowserConfig.java:12)
```
BrowserConfig.java:12 there variable `IS_REMOTE`
dependabot bot actions overwrites `IS_REMOTE` default value to String.empty()

**Comment by ylazakovich** [comment]
So, during so long time reviewing `dependabot` vs `renovate` - Renovate is the WINNER
